try{
    harry
}
catch(err){
    console.log(err.name)    
    console.log(err.message)    

}